Asset Management/config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users

  resources :categories, except: :show do
    get 'filter', on: :collection
    post 'new_peripheral', on: :member
  end

  resources :users do
    get 'manager', on: :collection
  end

  resources :user_home_categories, except: %i[show edit update]

  resources :combined_bookings, only: [] do
    member do
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :bookings, except: %i[new show] do
    collection do
      get 'requests'
      get 'accepted'
      get 'ongoing'
      get 'completed'
      get 'rejected'
      get 'late'
    end

    member do
      get 'booking_returned'
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :items do
    resources :bookings, except: %i[index show] do
      collection do
        get 'start_date'
        get 'end_date'
        get 'peripherals'
      end
    end

    collection do
      get 'import'
      post 'import_file'
      get 'manager'
      put 'update_manager_multiple'
      post 'change_manager_multiple'
      put 'update_manager_multiple_and_delete'
      get 'change_manager_multiple_and_delete'
    end

    member do
      get 'add_peripheral_option'
      get 'choose_peripheral'
      post 'add_peripheral'
      get 'add_parents'
      post 'add_parents_complete'
    end
  end

  resources :notifications, only: :index do
    put :mark_as_read, on: :collection
  end

  root to: 'home#index'

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Asset Management/app/models/booking.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bookings
#
#  id                  :integer          not null, primary key
#  start_date          :date
#  start_time          :time
#  end_date            :date
#  end_time            :time
#  start_datetime      :datetime
#  end_datetime        :datetime
#  reason              :string
#  next_location       :string
#  status              :integer
#  peripherals         :string
#  item_id             :integer
#  combined_booking_id :integer
#  user_id             :integer
#
# Indexes
#
#  index_bookings_on_combined_booking_id  (combined_booking_id)
#  index_bookings_on_item_id              (item_id)
#  index_bookings_on_user_id              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (combined_booking_id => combined_bookings.id)
#  fk_rails_...  (item_id => items.id)
#  fk_rails_...  (user_id => users.id)
#

# Booking model
class Booking < ApplicationRecord
  belongs_to :item, dependent: :destroy
  belongs_to :user
  belongs_to :combined_booking
  before_destroy :send_email_to_user
  after_destroy :destroy_combined_booking

  validates :start_date, :start_time,
            :end_date, :end_time,
            :next_location,
            :item, :user, :combined_booking, presence: true

  scope :find_by_user, ->(user) { where user: user }
  scope :item_owned_by, ->(user) { joins(:item).where(items: { user: user }) }
  scope :pending, -> { where status: 1 }
  scope :accepted, -> { where status: 2 }
  scope :ongoing, -> { where status: 3 }
  scope :completed, -> { where status: %w[4 6] }
  scope :rejected, -> { where status: 5 }
  scope :cancelled, -> { where status: 6 }
  scope :late, -> { where status: 7 }

  private

  def send_email_to_user
    UserMailer.user_booking_cancelled(self).deliver
    Notification.create(recipient: self.user, action: 'itemdeleted', notifiable: self, context: 'U')
  end

  def destroy_combined_booking
    combined_booking.destroy if combined_booking.bookings.blank?
  end
end

Asset Management/app/controllers/bookings_controller.rb
# frozen_string_literal: true

require 'irb'

# Handles the booking system
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  load_and_authorize_resource

  # Booking status {1: Pending, 2: Accepted, 3: Ongoing, 4: Completed,
  # 5: Rejected, 6: Cancelled, 7: Late}

  # GET /bookings
  def index
    @combined_bookings = CombinedBooking.find_by_user(current_user)
    @bookings = Booking.find_by_user(current_user)
  end

  # GET /bookings/requests
  def requests
    # Get bookings with items belonging to AM
    my_bookings = Booking.pending.item_owned_by(current_user).distinct.pluck(:combined_booking_id)

    # Get the parent combined bookings
    @combined_bookings = CombinedBooking.pending.where(id: my_bookings)
    combined_bookings_on_bookings = @combined_bookings.map{|cb| cb.bookings}.flatten

    # Get assets belonging to these combined bookings
    @bookings = Booking.where(id: combined_bookings_on_bookings)
  end

  # GET /bookings/accepted
  def accepted
    @combined_bookings = CombinedBooking.accepted.find_by_owner(current_user)
    @bookings = Booking.accepted.item_owned_by(current_user)
  end

  # GET /bookings/ongoing
  def ongoing
    @combined_bookings = CombinedBooking.ongoing.find_by_owner(current_user)
    @bookings = Booking.ongoing.item_owned_by(current_user)
  end

  # GET /bookings/completed
  def completed
    @combined_bookings = CombinedBooking.completed.find_by_owner(current_user)
    @bookings = Booking.completed.item_owned_by(current_user)
  end

  # GET /bookings/rejected
  def rejected
    @combined_bookings = CombinedBooking.rejected.find_by_owner(current_user)
    @bookings = Booking.rejected.item_owned_by(current_user)
  end

  # GET /bookings/late
  def late
    @combined_bookings = CombinedBooking.late.find_by_owner(current_user)
    @bookings = Booking.late.item_owned_by(current_user)
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @item = Item.find_by_id(params[:item_id])

    @parents = @item.get_item_parents
    @peripherals = @item.get_item_peripherals

    # Disable the unavaliable dates for an asset
    gon.initial_disable_dates = [fully_booked_days_single, fully_booked_days_multi].reduce([], :concat)

    # Select the defaut date and time
    unless gon.initial_disable_dates.blank?
      gon.initial_disable_dates.sort!
      gon.initial_start_date = initial_start_date
    end
  end

  # GET /bookings/1/edit
  def edit
    @item = @booking.item
    @parents = @item.get_item_parents
    @peripherals = @item.get_item_peripherals

    # Show the peripherals booked with parent asset
    @booking.peripherals = @booking.peripherals.tr('[]"', '') unless @booking.peripherals.blank?
  end

  # POST /bookings
  def create
    @booking = Booking.new(booking_params)

    # Converting the format
    @booking.start_datetime = @booking.start_date.to_s + ' ' + @booking.start_time.to_s
    @booking.end_datetime = @booking.end_date.to_s + ' ' + @booking.end_time.to_s
    @booking.next_location = params[:booking][:next_location].titleize
    @booking.reason = 'None' if params[:booking][:reason].blank?

    # Creating a combined booking
    item = @booking.item

    if item.user == current_user
      @booking.status = 2
      combined_booking = CombinedBooking.create(status: 1, user_id: current_user.id, owner_id: item.user_id)
      combined_booking.save
    else
      @booking.status = 1
      combined_booking = CombinedBooking.create(status: 1, user_id: current_user.id, owner_id: item.user_id)
      combined_booking.save
    end

    @booking.combined_booking_id = combined_booking.id

    # Create bookings for the chosen peripherals
    peripherals = params[:booking][:peripherals]

    # Changing the peripherals array into a string to be saved
    if peripherals.blank?
      @booking.peripherals = nil
    else
      peripherals_string = ''
      peripherals.each do |peripheral|
        next if peripheral == ''
        peripherals_string += ',' + Item.find_by_id(peripheral).serial
      end
      @booking.peripherals = peripherals_string[1..-1]
    end

    # Server side validation
    query = booking_validation(@booking.item_id, @booking.start_datetime, @booking.end_datetime)
    unless peripherals.blank?
      peripherals.each do |peripheral|
        next if peripheral == ''
        query &&= booking_validation(peripheral, @booking.start_datetime, @booking.end_datetime)
      end
    end

    if query && @booking.save
      # Making a booking for any peripheral selected
      unless peripherals.blank?
        peripherals.each do |peripheral|
          next if peripheral == ''
          booking = Booking.new(booking_params)

          booking.item_id = peripheral
          booking.start_datetime = @booking.start_datetime
          booking.end_datetime = @booking.end_datetime
          booking.next_location = params[:booking][:next_location].titleize
          booking.reason = 'None' if params[:booking][:reason].blank?
          booking.peripherals = nil
          booking.combined_booking_id = combined_booking.id
          booking.status = booking.item.user == current_user ? 2 : 1
          booking.save
        end
      end

      if combined_booking.bookings.blank?
        combined_booking.destroy
        redirect_to bookings_path, alert: 'Error occurred in the booking process. Please try again.'
      else
        # Check if all items on booking are the current user.
        if (combined_booking.bookings.all? { |b| b.status == 2})
          combined_booking.status = 2
          combined_booking.save
        end

        # Create notifications and send out the required emails
        Notification.create(recipient: item.user, action: 'requested', notifiable: @booking, context: 'AM')
        UserMailer.user_booking_requested(combined_booking).deliver

        combined_booking.sorted_bookings.each do |m|
          UserMailer.manager_booking_requested(m).deliver
        end

        redirect_to bookings_path, notice: 'Booking was successfully created.'
      end
    else
      redirect_to new_item_booking_path(item_id: @booking.item_id), alert: 'Chosen timeslot conflicts with other bookings.'
    end
  end

  # PATCH/PUT /bookings/1
  def update
    @booking.update(params.require(:booking).permit(:next_location, :reason, :item_id, :user_id))
    redirect_to bookings_path, notice: 'Booking was successfully updated.'
  end

  def set_booking_accepted
    booking = Booking.find(params[:id])
    booking.status = 2
    if booking.save
      # Create notifications and send our emails
      Notification.create(recipient: @booking.user, action: 'approved', notifiable: @booking, context: 'U')
      UserMailer.booking_approved([@booking]).deliver

      combined_booking = CombinedBooking.find(@booking.combined_booking_id)
      if combined_booking.bookings.where(status: %w[1 3 7]).blank?
        combined_booking.status = 2
      end
      combined_booking.save
    end

    # Rejects other bookings that have conflicts with the accepted booking
    item_id = booking.item.id
    item_bookings = Booking.where(item_id: item_id, status: 1)
    rejected = false
    item_bookings.each do |b|
      unless booking_validation(item_id, b.start_datetime, b.end_datetime)
        b.status = 5
        b.save
        Notification.create(recipient: b.user, action: 'rejected', notifiable: b, context: 'U')
        UserMailer.booking_rejected([b]).deliver
        reject_combined_booking = CombinedBooking.find(b.combined_booking_id)
        if reject_combined_booking.bookings.where(status: %w[1 2 3 4 7]).blank?
          reject_combined_booking.status = 5
        end
        reject_combined_booking.save
        rejected = true
      end
    end

    if rejected
      redirect_to requests_bookings_path, warning: 'Booking was successfully accepted,
        but another booking has been rejected as a result due to time conflicts.'
    else
      redirect_to requests_bookings_path, notice: 'Booking was successfully accepted.'
    end
  end

  def set_booking_rejected
    booking = Booking.find(params[:id])
    booking.status = 5
    if booking.save
      Notification.create(recipient: @booking.user, action: 'rejected', notifiable: @booking, context: 'U')
      UserMailer.booking_rejected([@booking]).deliver

      combined_booking = CombinedBooking.find(@booking.combined_booking_id)
      if combined_booking.bookings.where(status: %w[1 2 3 4 7]).blank?
        combined_booking.status = 5
      end
      combined_booking.save
    end

    redirect_to requests_bookings_path, notice: 'Booking was successfully rejected.'
  end

  # Set booking as cancelled
  def set_booking_cancelled
    @booking = Booking.find(params[:id])
    @booking.status = 6
    if @booking.save
      combined_booking = CombinedBooking.find(@booking.combined_booking_id)
      if combined_booking.bookings.where(status: %w[1 2 3 4 5 7]).blank?
        combined_booking.status = 6
        combined_booking.save
      end
      Notification.create(recipient: @booking.user, action: 'cancelled', notifiable: @booking, context: 'AM')
      UserMailer.manager_booking_cancelled([@booking]).deliver
      redirect_to bookings_path, notice: 'Booking was successfully cancelled.'
    end
  end

  # GET /bookings/1/booking_returned
  def booking_returned
    @item = @booking.item
  end

  # PUT /bookings/1/set_booking_returned
  def set_booking_returned
    booking = Booking.find(params[:id])
    booking.status = 4

    if booking.save
      combined_booking = CombinedBooking.find(booking.combined_booking_id)
      if combined_booking.bookings.where(status: %w[3 7]).blank?
        combined_booking.status = 4
        combined_booking.save
      end

      Notification.create(recipient: booking.user, action: 'returned', notifiable: booking, context: 'AM')
      UserMailer.manager_asset_returned([@booking]).deliver

      item = booking.item
      item.condition = params[:item][:condition]

Asset Management/app/views/bookings/_booking_status.html.haml
- case booking.status
- when 1
  %span.tag.is-warning.is-medium
    Pending
- when 2
  %span.tag.is-success.is-medium
    Accepted
- when 3
  %span.tag.is-info.is-medium
    Ongoing
- when 4
  %span.tag.is-success.is-medium
    Completed
- when 5
  %span.tag.is-danger.is-medium
    Rejected
- when 6
  %span.tag.is-danger.is-medium
    Cancelled
- when 7
  %span.tag.is-danger.is-medium
    Late
- else
  %span.tag.is-black.is-medium
    Unknown

Asset Management/app/views/bookings/_keywords.html.haml
- @bookings.where(combined_booking_id: id).each do |booking|
  #{booking.item.name} #{booking.item.serial}
  - case booking.status
  - when 1
    Pending
  - when 2
    Accepted
  - when 3
    Ongoing
  - when 4
    Completed
  - when 5
    Rejected
  - when 6
    Cancelled
  - when 7
    Late
  - else
    Unknown

Asset Management/app/views/bookings/_tabs.html.haml
.tabs.is-centered
  %ul
    %li{class:"#{current_class?(requests_bookings_path)}"}
      = link_to 'Requests', requests_bookings_path
    %li{class:"#{current_class?(accepted_bookings_path)}"}
      = link_to 'Accepted', accepted_bookings_path
    %li{class:"#{current_class?(ongoing_bookings_path)}"}
      = link_to 'Ongoing', ongoing_bookings_path
    %li{class:"#{current_class?(completed_bookings_path)}"}
      = link_to 'Completed', completed_bookings_path
    %li{class:"#{current_class?(rejected_bookings_path)}"}
      = link_to 'Rejected', rejected_bookings_path
    %li{class:"#{current_class?(late_bookings_path)}"}
      = link_to 'Late', late_bookings_path

Asset Management/app/views/bookings/accepted.html.haml
- content_for :title, "Accepted Bookings"

%br/
.container.is-fluid
  = render partial: 'layouts/flash'

  = render "tabs"

  %p.title.has-text-centered Accepted Bookings
  %table#bookings_other.table.is-striped.is-bordered
    %thead
      %tr
        %th Details
        %th ID
        %th Main Asset
        %th Start Date-Time
        %th End Date-Time
        %th Location
        %th Reason
        %th Booked By
        %th.is-hidden Keywords
    %tbody
      - @combined_bookings.each do |combined_booking|
        %tr
          %td.details-control{"data-target" => "row-#{combined_booking.id}"}
          %td.has-text-centered= combined_booking.id
          %td.has-text-centered= link_to combined_booking.bookings.first.item.name, combined_booking.bookings.first.item
          %td.has-text-centered= combined_booking.bookings.first.start_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.end_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.next_location
          %td.has-text-centered= combined_booking.bookings.first.reason
          %td.has-text-centered= link_to combined_booking.user.givenname, combined_booking.user
          %td.is-hidden
            = render 'keywords', id: combined_booking.id

        %tr.is-hidden{id: "row-#{combined_booking.id}"}
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
            = render 'keywords', id: combined_booking.id
          %td{colspan: 9}
            %table.table.is-striped.is-bordered
              %thead
                %tr
                  %th Asset Name
                  %th Serial
                  %th Status
                  %th Owner

              %tbody
                - @bookings.where(combined_booking_id: combined_booking.id).each do |booking|
                  %tr
                    %td.has-text-centered= link_to booking.item.name, booking.item
                    %td.has-text-centered= link_to booking.item.serial, booking.item
                    %td.has-text-centered
                      = render 'booking_status', booking: booking
                    %td.has-text-centered
                      = booking.item.user.givenname + " " + booking.item.user.sn

Asset Management/app/views/bookings/booking_returned.html.haml
- content_for :title, "Returning #{@item.name}"

%section.hero
  .hero-body
    .container.has-text-centered
      .column.is-10.is-offset-1
        %h3.title Returning #{@item.name}
        .box
          = simple_form_for @item, url: set_booking_returned_booking_path(@booking), method: :put do |f|
            .field.is-horizontal
              .field-label.is-normal
                %label.label The Item Is...
              .field-body
                .field{style: 'margin: auto'}
                  .control
                    = f.select :condition, options_for_select(['Like New', 'Good', 'Adequate', 'Damaged', 'Missing'], @item.condition), {}, {class: 'select2'}
            .field.is-horizontal
              .field-label.is-normal
                %label.label Further Info...
              .field-body
                .field{style: 'margin: auto'}
                  .control
                    = f.input :condition_info, label: false, placeholder: 'Scratched and dented', input_html: {class: 'input'}
            .field.is-horizontal
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Back', bookings_path, class: 'button is-light'
                  .control
                    = f.submit 'Return Item', class: 'button is-block is-success'

Asset Management/app/views/bookings/completed.html.haml
- content_for :title, "Completed Bookings"

%br/
.container.is-fluid
  = render partial: 'layouts/flash'

  = render "tabs"

  %p.title.has-text-centered Completed Bookings
  %table#bookings_other.table.is-striped.is-bordered
    %thead
      %tr
        %th Details
        %th ID
        %th Main Asset
        %th Start Date-Time
        %th End Date-Time
        %th Location
        %th Reason
        %th Booked By
        %th.is-hidden Keywords
    %tbody
      - @combined_bookings.each do |combined_booking|
        %tr
          %td.details-control{"data-target" => "row-#{combined_booking.id}"}
          %td.has-text-centered= combined_booking.id
          %td.has-text-centered= link_to combined_booking.bookings.first.item.name, combined_booking.bookings.first.item
          %td.has-text-centered= combined_booking.bookings.first.start_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.end_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.next_location
          %td.has-text-centered= combined_booking.bookings.first.reason
          %td.has-text-centered= link_to combined_booking.user.givenname, combined_booking.user
          %td.is-hidden
            = render 'keywords', id: combined_booking.id

        %tr.is-hidden{id: "row-#{combined_booking.id}"}
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
            = render 'keywords', id: combined_booking.id
          %td{colspan: 9}
            %table.table.is-striped.is-bordered
              %thead
                %tr
                  %th Asset Name
                  %th Serial
                  %th Status
                  %th Owner
              %tbody
                - @bookings.where(combined_booking_id: combined_booking.id).each do |booking|
                  %tr
                    %td.has-text-centered= link_to booking.item.name, booking.item
                    %td.has-text-centered= link_to booking.item.serial, booking.item
                    %td.has-text-centered
                      = render 'booking_status', booking: booking
                    %td.has-text-centered
                      = booking.item.user.givenname + " " + booking.item.user.sn

Asset Management/app/views/bookings/index.html.haml
- content_for :title, "My Bookings"

%br/
.container.is-fluid
  = render partial: 'layouts/flash'

  %p.title.has-text-centered My Bookings
  %p.title.has-text-centered
    = link_to 'Book an asset', items_path, class: 'button is-success'
  %table#bookings.table.is-striped.is-bordered
    %thead
      %tr
        %th Details
        %th ID
        %th Main Asset
        %th Peripherals
        %th Start Date-Time
        %th End Date-Time
        %th Location
        %th Reason
        %th Action
        %th.is-hidden Keywords
    %tbody
      - @combined_bookings.reverse_each do |combined_booking|
        %tr
          %td.details-control{"data-target" => "row-#{combined_booking.id}"}
          %td.has-text-centered= combined_booking.id
          %td.has-text-centered
            = link_to combined_booking.bookings.first.item.name, combined_booking.bookings.first.item
          %td.has-text-centered
            - if combined_booking.bookings.length > 1
              - combined_booking.bookings[1..-2].each do |booking|
                = link_to booking.item.name + ', ', booking.item
              = link_to combined_booking.bookings[-1].item.name, combined_booking.bookings[-1].item
          %td.has-text-centered= combined_booking.bookings.first.start_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.end_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.next_location
          %td.has-text-centered= combined_booking.bookings.first.reason
          %td.has-text-centered
            .buttons.is-centered
              - if combined_booking.status < 3
                = link_to set_booking_cancelled_combined_booking_path(combined_booking), data: { confirm: 'Are you sure you want cancel this booking?' }, method: :put, class: 'button is-danger' do
                  %span.icon
                    %i.fas.fa-ban
                  %span Cancel all
              - elsif (combined_booking.status == 3) || (combined_booking.status == 7)
                = link_to set_booking_returned_combined_booking_path(combined_booking), data: { confirm: 'Are you sure? If you would like to change any item conditions, please return them separately.' }, method: :put, class: 'button is-link' do
                  %span.icon
                    %i.fas.fa-redo
                  %span Return all
              - elsif (combined_booking.status == 4) || (combined_booking.status == 5) || (combined_booking.status == 6)
                = link_to new_item_booking_path(combined_booking.bookings.first.item.id), class: 'button is-link' do
                  %span.icon
                    %i.fas.fa-sync
                  %span Book Again
          %td.is-hidden
            = render 'keywords', id: combined_booking.id

        %tr.is-hidden{id: "row-#{combined_booking.id}"}
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
            = render 'keywords', id: combined_booking.id
          %td{:colspan => 10}
            %table.table.is-striped.is-bordered
              %thead
                %tr
                  %th Asset Name
                  %th Serial
                  %th Status
                  %th Action
              %tbody
                - @bookings.where(combined_booking_id: combined_booking.id).each do |booking|
                  %tr
                    %td.has-text-centered= link_to booking.item.name, booking.item
                    %td.has-text-centered= link_to booking.item.serial, booking.item
                    %td.has-text-centered
                      = render 'booking_status', booking: booking
                    %td.has-text-centered
                      .buttons.is-centered
                        - if booking.status < 3
                          = link_to 'Edit', edit_booking_path(booking.id), class: 'button is-link'
                          = link_to set_booking_cancelled_booking_path(booking), method: :put, class: 'button is-danger' do
                            %span.icon
                              %i.fas.fa-ban
                            %span Cancel Booking
                        - elsif (booking.status == 3) || (booking.status == 7)
                          = link_to booking_returned_booking_path(booking), class: 'button is-link' do
                            %span.icon
                              %i.fas.fa-redo
                            %span Return Item
                        - elsif (booking.status == 4) || (booking.status == 5) || (booking.status == 6)
                          = link_to new_item_booking_path(booking.item.id), class: 'button is-link' do
                            %span.icon
                              %i.fas.fa-sync
                            %span Book Again

Asset Management/app/views/bookings/requests.html.haml
- content_for :title, "Booking Requests"

%br/
.container.is-fluid
  = render partial: 'layouts/flash'

  = render "tabs"

  %p.title.has-text-centered Booking Requests
  %table#bookings_other.table.is-striped.is-bordered
    %thead
      %tr
        %th Details
        %th ID
        %th Main Asset
        %th Start Date-Time
        %th End Date-Time
        %th Location
        %th Reason
        %th Booked By
        %th Action
        %th.is-hidden Keywords
    %tbody
      - @combined_bookings.each do |combined_booking|
        %tr
          %td.details-control{"data-target" => "row-#{combined_booking.id}"}
          %td.has-text-centered= combined_booking.id
          %td.has-text-centered= link_to combined_booking.bookings.first.item.name, combined_booking.bookings.first.item
          %td.has-text-centered= combined_booking.bookings.first.start_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.end_datetime.strftime("%d %b %Y - %I:%M %p")
          %td.has-text-centered= combined_booking.bookings.first.next_location
          %td.has-text-centered= combined_booking.bookings.first.reason
          %td.has-text-centered= link_to combined_booking.user.givenname, combined_booking.user
          %td.has-text-centered
            .buttons.is-centered
              = link_to set_booking_accepted_combined_booking_path(combined_booking), data: { confirm: 'Are you sure?' }, method: :put, class: 'button is-success' do
                %span.icon
                  %i.fas.fa-check
                %span Accept all
              = link_to set_booking_rejected_combined_booking_path(combined_booking), data: { confirm: 'Are you sure?' }, method: :put, class: 'button is-danger' do
                %span.icon
                  %i.fas.fa-ban
                %span Reject all
          %td.is-hidden
            = render 'keywords', id: combined_booking.id

        %tr.is-hidden{id: "row-#{combined_booking.id}"}
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
          %td.is-hidden
            = render 'keywords', id: combined_booking.id
          %td{colspan: 10}
            %table.table.is-striped.is-bordered
              %thead
                %tr
                  %th Asset Name
                  %th Serial
                  %th Status
                  %th Owner
                  %th Action
              %tbody
                - @bookings.where(combined_booking_id: combined_booking.id).each do |booking|
                  %tr
                    %td.has-text-centered= link_to booking.item.name, booking.item
                    %td.has-text-centered= link_to booking.item.serial, booking.item
                    %td.has-text-centered
                      = render 'booking_status', booking: booking
                    %td.has-text-centered
                      = booking.item.user.givenname + " " + booking.item.user.sn
                    %td.has-text-centered
                      .field.is-grouped.is-grouped-centered
                        - if (booking.item.user == current_user) && (booking.status == 1)
                          %p.control
                            = form_tag set_booking_accepted_booking_path(booking), method: :put do
                              = submit_tag 'Accept', class: 'button is-block is-success', id: "accept_single_booking#{booking.id}"
                          %p.control
                            = form_tag set_booking_rejected_booking_path(booking), method: :put do
                              = submit_tag 'Reject', class: 'button is-block is-danger', id: "reject_single_booking#{booking.id}"
                        - else
                          No Actions