Asset Management/config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users

  resources :categories, except: :show do
    get 'filter', on: :collection
    post 'new_peripheral', on: :member
  end

  resources :users do
    get 'manager', on: :collection
  end

  resources :user_home_categories, except: %i[show edit update]

  resources :combined_bookings, only: [] do
    member do
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :bookings, except: %i[new show] do
    collection do
      get 'requests'
      get 'accepted'
      get 'ongoing'
      get 'completed'
      get 'rejected'
      get 'late'
    end

    member do
      get 'booking_returned'
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :items do
    resources :bookings, except: %i[index show] do
      collection do
        get 'start_date'
        get 'end_date'
        get 'peripherals'
      end
    end

    collection do
      get 'import'
      post 'import_file'
      get 'manager'
      put 'update_manager_multiple'
      post 'change_manager_multiple'
      put 'update_manager_multiple_and_delete'
      get 'change_manager_multiple_and_delete'
    end

    member do
      get 'add_peripheral_option'
      get 'choose_peripheral'
      post 'add_peripheral'
      get 'add_parents'
      post 'add_parents_complete'
    end
  end

  resources :notifications, only: :index do
    put :mark_as_read, on: :collection
  end

  root to: 'home#index'

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Asset Management/app/views/layouts/_flash.html.haml
- if (not notice.blank?) || (not alert.blank?) || (not warning.blank?)
  .columns
    .column.is-4.is-offset-4
      - if notice
        .notification.is-success.has-text-centered
          %button.delete
          = notice
      - elsif alert
        .notification.is-danger.has-text-centered
          %button.delete
          = alert
      - else
        .notification.is-warning.has-text-centered
          %button.delete
          = warning

Asset Management/app/views/layouts/application.html.haml
!!!
%html.has-navbar-fixed-top{:lang => "en"}
  %head
    / Required meta tags
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "ZerJun Eng", :name => "author"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tag
    = include_gon(init: true)

    / Favicon
    = favicon_link_tag 'favicon/apple-touch-icon.png', rel: 'apple-touch-icon', sizes: '180x180'
    = favicon_link_tag 'favicon/favicon-32x32.png', rel: 'icon', sizes: '32x32', type: 'image/png'
    = favicon_link_tag 'favicon/favicon-16x16.png', rel: 'icon', sizes: '16x16', type: 'image/png'
    = favicon_link_tag 'favicon/site.webmanifest', rel: 'manifest'
    = favicon_link_tag 'favicon/safari-pinned-tab.svg', rel: 'mask-icon', color: '#5bbad5'
    = favicon_link_tag 'favicon/favicon.ico', rel: 'shortcut icon'
    %meta{:content => "#da532c", :name => "msapplication-TileColor"}/
    %meta{:content => "#{asset_path 'favicon/browserconfig.xml'}", :name => "msapplication-config"}/
    %meta{:content => "#ffffff", :name => "theme-color"}/

    / Bulma CSS, Material Icons, Font Awesome
    = stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"
    = stylesheet_link_tag '//fonts.googleapis.com/icon?family=Material+Icons'
    = stylesheet_link_tag '//use.fontawesome.com/releases/v5.0.13/css/all.css'
    = stylesheet_link_tag 'application'

    %title #{content_for(:title)} - AMRC Asset Management System

  %body
    %noscript
      %meta{'http-equiv' => 'refresh', :content => "0;URL=#{javascript_warning_path}"}/

    %nav.navbar.is-fixed-top.is-light
      .navbar-brand
        = link_to root_path, class: "navbar-item #{current_class?(root_path)}" do
          = image_tag("amrc_home.svg", width: "75")
        .dropdown.is-active.is-hidden-desktop#mobile_notification_dropdown
          .dropdown-trigger{"data-behavior" => "notification-link"}
            %button.button{"aria-haspopup" => "true", "aria-controls" => "dropdown-menu"}
              %span.icon
                %i.fas.fa-bell.notifications-bell
                %span{"data-behavior" => "unread-count"}
          .dropdown-menu#dropdown-menu{:role => "menu"}
            .dropdown-content{"data-behavior" => "notification-items-mobile" }
        .navbar-burger.burger{"data-target" => "navbarExampleTransparentExample"}
          %span
          %span
          %span
      #navbarExampleTransparentExample.navbar-menu{"data-behavior" => "notifications"}
        .navbar-start
          .navbar-item.has-dropdown.is-hoverable
            %a.navbar-link
              %p Browse by <br class="is-hidden-widescreen"><strong>Categories</strong>
            .navbar-dropdown.is-boxed
              - categories = Category.take(5)
              - categories.each do |category|
                = link_to category.name, items_path(category_name: category.name), class: "navbar-item"
              = link_to 'View All', filter_categories_path, class: "navbar-item"
          = link_to 'Assets', items_path, class: "navbar-item #{current_class?(items_path)}"
          = link_to 'Asset Managers', manager_users_path, class: "navbar-item #{current_class?(manager_users_path)}"
          - if can?(:read, Category)
            = link_to 'Categories', categories_path, class: "navbar-item #{current_class?(categories_path)} is-hidden-custom"
            - if can?(:read, User)
              = link_to 'Users', users_path, class: "navbar-item #{current_class?(users_path)} is-hidden-custom"
          - if can?(:read, Category)
            .navbar-item.has-dropdown.is-hoverable.is-hidden.is-show-custom
              %a.navbar-link
                %p More
              .navbar-dropdown.is-boxed
                = link_to 'Categories', categories_path, class: "navbar-item #{current_class?(categories_path)}"
                - if can?(:read, User)
                  = link_to 'Users', users_path, class: "navbar-item #{current_class?(users_path)}"

        .navbar-end
          - if can?(:manage, Booking)
            .navbar-item.has-dropdown.is-hoverable
              = link_to requests_bookings_path, class: 'navbar-link' do
                Asset <br class="is-hidden-widescreen"> Requests
              .navbar-dropdown.is-boxed.is-right
                = link_to 'Requests', requests_bookings_path, class: "navbar-item #{current_class?(requests_bookings_path)}"
                = link_to 'Accepted Bookings', accepted_bookings_path, class: "navbar-item #{current_class?(accepted_bookings_path)}"
                = link_to 'Ongoing Bookings', ongoing_bookings_path, class: "navbar-item #{current_class?(ongoing_bookings_path)}"
                = link_to 'Completed Bookings', completed_bookings_path, class: "navbar-item #{current_class?(completed_bookings_path)}"
                = link_to 'Rejected Bookings', rejected_bookings_path, class: "navbar-item #{current_class?(rejected_bookings_path)}"
                = link_to 'Late Bookings', late_bookings_path, class: "navbar-item #{current_class?(late_bookings_path)}"
            .navbar-item.has-dropdown.is-hoverable
              %a.navbar-link
                Create
              .navbar-dropdown.is-boxed.is-right
                = link_to 'Asset', new_item_path, class: "navbar-item #{current_class?(new_item_path)}"
                = link_to 'Peripheral', new_item_path(is_peripheral: true), class: "navbar-item #{current_class?(new_item_path(is_peripheral: true))}"
                = link_to 'Category', new_category_path, class: "navbar-item #{current_class?(new_category_path)}"
                - if can?(:manage, User)
                  = link_to 'User', new_user_path, class: "navbar-item #{current_class?(new_user_path)}"
          .navbar-item.has-dropdown.is-hoverable.is-hidden-touch{"data-behavior" => "notification-link"}
            %a.navbar-link
              %span.badge.is-badge-danger{"data-behavior" => "unread-count"}
                %span.icon
                  %i.fas.fa-bell.notifications-bell
            .navbar-dropdown.is-boxed.is-right{"data-behavior" => "notification-items"}
          .navbar-item.has-dropdown.is-hoverable
            %a.navbar-link
              %span.icon
                %i.fas.fa-user
              %span
                #{current_user.givenname}
            .navbar-dropdown.is-boxed.is-right
              - if can?(:create, Item)
                = link_to 'My Assets', manager_items_path(user_id: current_user.id), class: "navbar-item #{current_class?(manager_items_path(user_id: current_user.id))}"
              = link_to 'My Bookings', bookings_path, class: "navbar-item #{current_class?(bookings_path)}"
              = link_to 'My Profile', current_user, class: "navbar-item #{current_class?("/users/#{current_user.id}")}"
              = link_to 'Manage Favourites', user_home_categories_path, class: "navbar-item #{current_class?(user_home_categories_path)}"
              = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "navbar-item", id: "sign_out"
    = yield

    / jQuery, Datatable, bunnyJS, momentJS
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    = javascript_include_tag "//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"
    = javascript_include_tag "//unpkg.com/bunnyjs@0.14.41/dist/element.min.js"
    = javascript_include_tag "//unpkg.com/bunnyjs@0.14.41/dist/validation.min.js"
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"
    = javascript_include_tag "application"

Asset Management/app/views/layouts/errors.html.haml
%section.hero.is-large
  .hero-body
    .container
      .columns
        .column.is-3.is-offset-2
          %h1.title{:style => "font-size: 70px;color:#ff470f"}= error_code
          %h2.subtitle.is-30= error_message
        .column.is-5
          %p
            Sorry, there was a problem, please try again.
          %br
          %p
            If you continue to see this message please send a description of the problem to:
            = mail_to "support@epigenesys.org.uk"