Asset Management/config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users

  resources :categories, except: :show do
    get 'filter', on: :collection
    post 'new_peripheral', on: :member
  end

  resources :users do
    get 'manager', on: :collection
  end

  resources :user_home_categories, except: %i[show edit update]

  resources :combined_bookings, only: [] do
    member do
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :bookings, except: %i[new show] do
    collection do
      get 'requests'
      get 'accepted'
      get 'ongoing'
      get 'completed'
      get 'rejected'
      get 'late'
    end

    member do
      get 'booking_returned'
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :items do
    resources :bookings, except: %i[index show] do
      collection do
        get 'start_date'
        get 'end_date'
        get 'peripherals'
      end
    end

    collection do
      get 'import'
      post 'import_file'
      get 'manager'
      put 'update_manager_multiple'
      post 'change_manager_multiple'
      put 'update_manager_multiple_and_delete'
      get 'change_manager_multiple_and_delete'
    end

    member do
      get 'add_peripheral_option'
      get 'choose_peripheral'
      post 'add_peripheral'
      get 'add_parents'
      post 'add_parents_complete'
    end
  end

  resources :notifications, only: :index do
    put :mark_as_read, on: :collection
  end

  root to: 'home#index'

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Asset Management/app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id               :integer          not null, primary key
#  name             :string
#  condition        :string
#  location         :string
#  manufacturer     :string
#  model            :string
#  serial           :string
#  acquisition_date :date
#  purchase_price   :decimal(, )
#  image            :string
#  keywords         :string
#  po_number        :string
#  condition_info   :string
#  comment          :string
#  retired_date     :date
#  user_id          :integer
#  category_id      :integer
#
# Indexes
#
#  index_items_on_category_id  (category_id)
#  index_items_on_serial       (serial) UNIQUE
#  index_items_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#

# Item model
class Item < ApplicationRecord
  attr_accessor :add_parents
  attr_accessor :add_peripherals
  attr_accessor :is_peripheral

  belongs_to :category
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :combined_bookings, through: :bookings, dependent: :destroy
  has_many :parent_items, class_name: 'ItemPeripheral', foreign_key: :parent_item_id, dependent: :destroy
  has_many :peripheral_items, class_name: 'ItemPeripheral', foreign_key: :peripheral_item_id, dependent: :destroy

  validates :name, :condition, :location, :category, :user, presence: true
  validates :serial, presence: true, uniqueness: true

  scope :name_serial, -> { pluck(:name, :serial) }
  scope :manufacturer_uniq, -> { pluck(:manufacturer).uniq }

  mount_uploader :image, ImageUploader

  def available?
    bookings.ongoing.blank?
  end

  def get_item_peripherals
    peripherals_for_item = ItemPeripheral.where(parent_item: self)
    peripherals_for_item.map(&:peripheral_item)
  end

  def get_item_parents
    parents_for_item = ItemPeripheral.where(peripheral_item: self)
    parents_for_item.map(&:parent_item)
  end
end

Asset Management/app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  phone              :string
#  permission_id      :integer
#  email              :string           default(""), not null
#  sign_in_count      :integer          default(0), not null
#  current_sign_in_at :datetime
#  last_sign_in_at    :datetime
#  current_sign_in_ip :inet
#  last_sign_in_ip    :inet
#  username           :string
#  uid                :string
#  mail               :string
#  ou                 :string
#  dn                 :string
#  sn                 :string
#  givenname          :string
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_username  (username)
#

# User model
class User < ApplicationRecord
  include EpiCas::DeviseHelper

  has_many :combined_bookings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :user_home_categories, dependent: :destroy
  has_many :categories, through: :user_home_categories
  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy

  validates_format_of :phone, with: /\A([1-9])([0-9]{9})\z/, allow_blank: true
  validates :email, :username, presence: true, uniqueness: true
  validates :permission_id, presence: true

  def generate_attributes_from_ldap_info
    self.username = uid
    self.email = mail
    super # This needs to be left in so the default fields are also set
  end

  def user?
    permission_id == 1
  end

  def asset_manager?
    permission_id == 2
  end

  def admin?
    permission_id == 3
  end

  def no_asset?
    items.blank?
  end
end

Asset Management/app/controllers/items_controller.rb
# frozen_string_literal: true

require 'irb'

# Item controller
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /items
  def index
    # Get all items
    @items = Item.all

    # Pass category name to js
    gon.category = params[:category_name]
  end

  # GET /items/manager
  def manager
    # Failsafe for errors. Ensures a standard a standard user cannot see their "items" page.
    if params[:user_id].to_i == current_user.id && current_user.user?
      render 'errors/error_404'
    else
      # Get the user object for the given manager
      @manager = User.find_by_id(params[:user_id])

      # If the user selects the on loan tab, fill array with assets which are on booking or late.
      if params[:tab] == 'OnLoan'
        @bookings = Booking.joins(:item).where(status: %w[3 7], items: {user_id: current_user.id})
      # If the user selects issue tab, generate a list of items where the condition is low
      elsif params[:tab] == 'Issue'
        @items = Item.where(user_id: current_user.id, condition: %w[Damaged Missing])
      # Standard tab. Display all of a user's assets
      else
        @items = Item.where(user_id: params[:user_id])
      end
    end
  end

  # GET /items/1
  def show
    # Get bookings for a given item
    @bookings = Booking.joins(:user).where(item_id: @item.id)

    # If a peripheral, get the item's parents
    @parents = @item.get_item_parents

    # If an item has peipherals, fetch a list of them.
    @peripherals = @item.get_item_peripherals
  end

  # GET /items/1/add_peripheral_option
  def add_peripheral_option
    # Get the item that a peripheral will be added to
    @item = Item.find_by_id(params[:id])
  end

  # GET /items/1/choose_peripheral
  def choose_peripheral
    @item = Item.find_by_id(params[:id])

    # Get all items ellegible to have a peripheral added
    @items = Item.where.not(serial: @item.serial)

    # Validate these choices
    Item.all.each do |i|
      if !i.peripheral_items.where(parent_item_id: @item.id).blank? || !i.parent_items.where(peripheral_item_id: @item.id).blank?
        @items -= [i]
      end
    end
  end

  # POST /items/1/add_peripheral
  def add_peripheral
    # Get the item a peripheral will be added to
    @item = Item.find_by_id(params[:id])

    # Check a peripheral was selected
    if params[:item][:add_peripherals].length == 1
      redirect_to @item, warning: 'No peripheral was added.'
    else
      peripherals = params[:item][:add_peripherals]

      peripherals.each do |peripheral|
        unless peripheral.blank?
          # Find the selected peripheral item
          new_peripheral = Item.find_by_id(peripheral.to_i)
          # Create the allowed pair of peripheral and item
          pair = ItemPeripheral.create(parent_item_id: @item.id, peripheral_item_id: new_peripheral.id)

          # Save the pair and changes to the item.
          pair.save
        end
      end

      @item.save

      redirect_to @item, notice: 'Peripheral was successfully added'
    end
  end

  # GET /items/new
  def new
    # Get all items
    @items = Item.all

    # Pass parent item id to javascript where creating a peripheral
    unless params[:item_id].blank?
      @parent = Item.find_by(id: params[:item_id])
      gon.parent_id = params[:item_id]
    end
  end

  # GET /items/1/edit
  def edit
    # If this item is a peripheral of another
    if params[:is_peripheral] == 'true'
      # Get all other items
      @items = Item.where.not(id: @item.id)
      Item.all.each do |i|
        # Validate and return potential parent items
        unless i.peripheral_items.where(parent_item_id: @item.id).blank?
          @items = @items - [i]
        end
      end

      # Get an item's actual parents
      @parents = @item.get_item_parents

      # Send each of item's parent's ids to js
      gon.parent_id = []
      @parents.each do |parent|
        gon.parent_id.append(parent.id)
      end
    end
  end

  # POST /items
  def create
    # Create an object for the item being added to database
    @item = Item.new(item_params)

    # Set fields from form
    @item.user_id = current_user.id
    @item.serial = params[:item][:serial].upcase.strip
    @item.location = params[:item][:location].titleize.strip

    # try / catch for saving to database
    if @item.save
      # Add peripheral items
      unless params[:item][:is_peripheral].blank?
        # Get parent items
        parents = params[:item][:add_parents]

        #Set created item as peripheral item
        peripheral = @item.id

        # Loop through each parent item and create pairs of allowed peripherals recursively
        parents.each do |parent|
          unless parent.blank?
            pair = ItemPeripheral.create(parent_item_id: parent.to_i, peripheral_item_id: peripheral)
            pair.save
          end
        end
      end

      redirect_to @item, notice: 'Asset was successfully created.'
    else
      redirect_to request.referrer, alert: 'The serial is already in use or invalid information provided.'
    end
  end

  # PATCH/PUT /items/1
  def update
    @item.update(item_params)

    # Format location input on form
    @item.serial = params[:item][:serial].upcase.strip
    @item.location = params[:item][:location].titleize.strip

    # Update semi-dependent fields if item marked as retired
    if params[:item][:condition] == 'Retired' && @item.retired_date.blank?
      @item.retired_date = Date.today
    elsif params[:item][:condition] != 'Retired' && !@item.retired_date.blank?
      @item.retired_date = nil
    end

    # Save the item
    if @item.save

      # If the item has parents or peripherals update these too
      unless params[:item][:is_peripheral].blank?

        parents = params[:item][:add_parents]

        # Set @item as peripheral variable
        peripheral = @item.id

        # Get the original parents before record updated
        original_parents = @item.get_item_parents
        deleted_parents = original_parents

        # For each parent item create new paits of peripheral and item
        # Remove pairs for deleted peripherals/parents
        parents.each do |parent|
          unless parent.blank?
            new_parent = Item.find(parent.to_i)

            # Remove old parents
            unless deleted_parents.blank?
              deleted_parents -= [new_parent]
            end

            # Create recursive peripheral pairings
            unless @item.get_item_parents.include? new_parent
              pair = ItemPeripheral.create(parent_item_id: parent.to_i, peripheral_item_id: peripheral)
              pair.save
            end
          end
        end

        deleted_parents.each do |deleted_parent|
          ItemPeripheral.where(parent_item_id: deleted_parent.id, peripheral_item_id: peripheral).first.destroy
        end
      end
      redirect_to @item, notice: 'Asset was successfully updated.'
    else
      redirect_to request.referrer, alert: 'Serial already exist or invalid information provided'
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_path, notice: 'Asset was successfully deleted.'
  end

  # GET /items/change_manager_multiple
  def change_manager_multiple
    # Used by simpleform as selected entities will be objects.
    @item = Item.new
    # Show users who have sufficient permissions and are not the current user as options
    @allowed_user = User.where.not(id: current_user.id, permission_id: 1)
  end

  # POST /items/change_manager_multiple
  def update_manager_multiple
    # Get the ids of selected items on previous page
    item_ids = params[:item][:item_id_list].split(' ')

    # Get items from db using this id
    @items = Item.where(id: item_ids)

    # Update the owner of each of these items
    @items.each do |item|
      item.user_id = params[:item][:user_id]
      item.save
    end

    redirect_to manager_items_path(user_id: current_user.id), notice: 'Ownership was successfully transfered.'
  end

  # GET /items/change_manager_multiple
  def change_manager_multiple_and_delete
    # Used by simpleform as selected entities will be objects.
    @item = Item.new
    @user = User.find_by_id(params[:user_id])
    # Get a list of users that can be transferred to
    @allowed_user = User.where.not(id: params[:user_id], permission_id: 1)
  end

  # POST /items/change_manager_multiple
  def update_manager_multiple_and_delete
    # Get items belonging to the user being deleted
    @items = Item.where(user_id: params[:item][:old_id])

    # Transfer each item to a new owner and save it
    @items.each do |item|
      item.user_id = params[:item][:user_id]
      item.save
    end

    # Get the original owner of the assets
    @user = User.find(params[:item][:old_id])

    # Finally destroy the user
    if @user.destroy
      redirect_to users_path, notice: 'User was successfully deleted.'
    end
  end

  # GET /items/import
  def import; end

  # POST /items/import_file
  def import_file

    # Get import file
    excel_import = Importers::ItemImporter.new(params[:import_file][:file].tempfile.path)
    res = excel_import.import(current_user)

    # Error message 0
    if res[0].zero?
      redirect_to import_items_path, alert: 'The submitted file is not of file .xlsx format'
    # Error message 1
    elsif res[0] == 1
      redirect_to import_items_path, alert: 'Headers of excel sheet do not match appropriate format'
    elsif res[0] == 2
      incorrect_rows = res[1]
      if incorrect_rows.blank?
        redirect_to import_items_path, notice: 'Import was successful and no problems occured'
      else
        redirect_to controller: 'items', action: 'import', incorrect_rows: incorrect_rows, alert: 'Import was partially successful, view rows that had problems below'
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item

Asset Management/app/views/items/_item_condition.html.haml
- case item.condition
- when 'Like New'
  %span.tag.is-success.is-medium
    = item.condition
- when 'Good'
  %span.tag.is-primary.is-medium
    = item.condition
- when 'Adequate'
  %span.tag.is-warning.is-medium
    = item.condition
- when 'Damaged'
  %span.tag.is-danger.is-medium
    = item.condition
- when 'Missing'
  %span.tag.is-danger.is-medium
    = item.condition
- when 'Retired'
  %span.tag.is-danger.is-medium
    = item.condition
- else
  %span.tag.is-black.is-medium
    Unknown

Asset Management/app/views/items/add_peripheral_option.html.haml
- content_for :title, "Add peripheral for #{@item.name}"

%section.section
  .container.is-fluid.has-text-centered
    %h3.title Add peripheral for #{@item.name}

    .columns
      .column.is-3.is-offset-3
        .card
          .card-content
            %p.subtitle Choose from an existing asset
          %footer.card-footer
            %p.card-footer-item
              = link_to 'Choose', choose_peripheral_item_path, class: 'button is-link'
      .column.is-3
        .card
          .card-content
            %p.subtitle Create a new asset
          %footer.card-footer
            %p.card-footer-item
              = link_to 'Create', new_item_path(item_id: @item.id, is_peripheral: true), class: 'button is-primary'

Asset Management/app/views/items/change_manager_multiple.html.haml
- content_for :title, "Transferring ownership"

%section.hero
  .hero-body
    .container.has-text-centered
      .column.is-10.is-offset-1
        %h3.title Transfer My Assets To...
        .box
          = simple_form_for @item, url: update_manager_multiple_items_path, method: :put do |f|
            .field.is-horizontal
              .field-label.is-normal
                %label.label Owner
              .field-body
                .field{style: 'margin: auto'}
                  .control
                    = f.hidden_field :item_id_list, value: params[:item_ids]
                    = f.association :user, label: false, input_html: {class: 'select2'}, collection: @allowed_user.map { |u| [u.givenname, u.id] }, include_blank: false

            .field.is-horizontal
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Cancel' , items_path, class: 'button is-light'
                  .control
                    = f.submit 'Save changes', class: 'button is-block is-success'

Asset Management/app/views/items/change_manager_multiple_and_delete.html.haml
- content_for :title, "Transferring ownership"

%section.hero
  .hero-body
    .container.has-text-centered
      .column.is-10.is-offset-1
        %h3.title Transfer #{@user.givenname} Assets To...
        .box
          = simple_form_for @item, url: update_manager_multiple_and_delete_items_path, method: :put do |f|
            .field.is-horizontal
              .field-label.is-normal
                %label.label Owner
              .field-body
                .field{style: 'margin: auto'}
                  .control
                    = f.hidden_field :old_id, value: params[:user_id]
                    = f.association :user, label: false, input_html: {class: 'select2'}, collection: @allowed_user.map { |u| [u.givenname, u.id]}, include_blank: false

            .field.is-horizontal
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Cancel', edit_user_path(@user), class: 'button is-light'
                  .control
                    = f.submit 'Save changes', class: 'button is-block is-success'

Asset Management/app/views/items/choose_peripheral.html.haml
- content_for :title, "Choose an existing asset as peripheral"

%section.hero
  .hero-body
    .container.has-text-centered
      .column.is-10.is-offset-1
        %h3.title Add peripheral for #{@item.name} (#{@item.serial})
        .box
          = simple_form_for @item, url: add_peripheral_item_path, method: :post do |f|
            .field.is-horizontal
              .field-label.is-normal
                %label.label Peripheral Asset
              .field-body
                .field
                  .control
                    = f.select :add_peripherals, @items.map { |i| [i.name + ' (' + i.serial + ')', i.id] }, {}, {class: 'select2', multiple: ''}
            %br
            %br
            .field.is-horizontal
              .field-label.has-text-left
                -# Left empty for spacing
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Cancel', @item, class: 'button is-light'
                  .control
                    = f.submit 'Add as Peripheral', class: 'button is-block is-link', id: 'submitButton'

Asset Management/app/views/items/import.html.haml
- content_for :title, "Import assets from file"

%section.hero
  .hero-body
    .container.has-text-centered
      = render partial: 'layouts/flash'

      .column.is-10.is-offset-1
        %h3.title Import assets
        .box
          = simple_form_for :import_file, url: import_file_items_path, html: { multipart: true } do |f|
            = f.error_notification

            .field.is-horizontal
              .field-label.is-normal
                %label.label Upload file
              .field-body
                .field
                  .file.has-name.is-fullwidth
                    %label.file-label
                      = f.input :file, label: false, input_html: {class: 'file-input', type: 'file', accept: '.xlsx'}
                      %span.file-cta
                        %span.file-icon
                          %i.fas.fa-upload
                        %span.file-label
                          Choose a file…
                      %span.file-name#file_name
                        Uploaded file name
                  %p.help Only .xlsx files are allowed
            %br
            .field.is-horizontal
              .field-label.has-text-left
                -#Left empty for spacing
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Cancel' , root_path, class: 'button is-block is-light'
                  .control
                    = f.submit 'Import assets', class: 'button is-block is-link'
      - if !params[:incorrect_rows].blank?
        %br
        %br
        %br
        %br
        %p.title.has-text-centered Import Errors
        %table#categories.table.is-striped.is-bordered
          %thead
            %tr
              %th Row
              %th Error
              %th Example
          %tbody
            - params[:incorrect_rows].each do |row|
              %tr
                %td.has-text-centered
                  = row[0].split(",").first.to_i + 2
                %td.has-text-centered
                  - case row[0].split(",").last.to_i
                  - when 0
                    This row's NAME cell is either empty or does not follow the correct format
                  - when 1
                    This row's SERIAL cell is either empty or does not follow the correct format
                  - when 2
                    This row's SERIAL cell already exists in the database and is not unique
                  - when 3
                    This row's CATEGORY cell is empty
                  - when 4
                    This row's CATEGORY cell does not exist in the database
                  - when 5
                    This row's CONDITION cell is either empty or does not follow the correct format
                  - when 6
                    This row's ACQUISITION_DATE cell does not follow the correct format
                  - when 7
                    This row's PURCHASE_PRICE cell does not follow the correct format
                  - when 8
                    This row's LOCATION cell is either empty or does not follow the correct format
                  - when 9
                    This row's MANUFACTURER cell does not follow the correct format
                  - when 10
                    This row's MODEL cell does not follow the correct format
                  - when 11
                    One of the peripheral assets in this row's PERIPHERALS cell does not exist in the database
                  - when 12
                    This row's RETIRED_DATE cell either does not follow the correct format or CONDITION is not set to Retired
                  - when 13
                    This row's PO_NUMBER cell does not follow the correct format
                  - when 14
                    This row's COMMENT cell does not follow the correct format
                  - when 15
                    This row's KEYWORDS cell does not follow the correct format
                  - else
                    Unknown
                %td.has-text-centered
                  - case row[0].split(",").last.to_i
                  - when 0
                    An appropriate NAME should be a STRING or TEXT
                  - when 1
                    An appropriate SERIAL should be a STRING or TEXT
                  - when 2
                    Please check the database whether this item has been added before, or use a different SERIAL
                  - when 3
                    An appropriate CATEGORY should be a STRING or TEXT
                  - when 4
                    Please check whether the category already exists in the database, if not you may create one and import it again
                  - when 5
                    An appropriate NAME should be one of the following: Like New/Good/Adequate/Damaged/Missing/Retired
                  - when 6
                    An appropriate ACQUISITION_DATE should be a legit DATE
                  - when 7
                    An appropriate PURCHASE_PRICE should be a FLOAT or INTEGER
                  - when 8
                    An appropriate LOCATION should be a STRING or TEXT
                  - when 9
                    An appropriate MANUFACTURER should be a STRING or TEXT
                  - when 10
                    An appropriate MODEL should be a STRING or TEXT
                  - when 11
                    Please check if all the peripheral asset exists in the database or if there is any typos
                  - when 13
                    An appropriate RETIRED_DATE should be in the DATE format and the CONDITION should be 'Retired'
                  - when 14
                    An appropriate PO_NUMBER should be a STRING or TEXT
                  - when 15
                    An appropriate COMMENT should be a STRING or TEXT
                  - when 15
                    Appropriate KEYWORDS should be STRING or TEXT separated by spaces
                  - else
                    Unknown

Asset Management/app/views/items/show.html.haml
- content_for :title, "#{@item.name}"

%section.section
  .container.is-desktop
    = render partial: 'layouts/flash'

    .box
      .columns
        - if @item.image?
          .column.is-5.has-text-centered#zoom{style: 'margin: auto'}
            = image_tag(@item.image.url, alt: 'Image')
        -else
          .column.is-5.has-text-centered{style: 'margin: auto'}
            = image_tag("amrc.svg", width: "250", alt: 'Default Image, AMRC')
        .column
          %table.table.is-bordered.is-striped.is-fullwidth
            %tbody
              %tr
                %th Owner
                %td
                  = @item.user.givenname.to_s + ' ' + @item.user.sn.to_s
              - unless @parents.blank?
                %tr
                  %th Parent Assets
                  %td
                    - @parents.each do |parent|
                      = link_to "#{parent.name + ' (' + parent.serial + ')' }", parent, class: 'button'
              %tr
                %th Name
                %td
                  = @item.name
              %tr
                %th Manufacturer
                %td
                  = @item.manufacturer
              %tr
                %th Model
                %td
                  = @item.model
              %tr
                %th Serial
                %td
                  = @item.serial
              %tr
                %th Category
                %td
                  = @item.category.name
              %tr
                %th PO Number
                %td
                  = @item.po_number
              %tr
                %th Acquisition Date
                %td
                  = @item.acquisition_date.strftime("%d %B %Y") unless @item.acquisition_date.blank?
              %tr
                %th Purchase Price
                %td
                  = "£ " + @item.purchase_price.to_s
              %tr
                %th Condition
                %td
                  = render 'item_condition', item: @item
              %tr
                %th Storage Location
                %td
                  = @item.location
              %tr
                %th Peripherals
                %td
                  .buttons
                    - unless @peripherals.blank?
                      - @peripherals.each do |peripheral|
                        = link_to "#{peripheral.name + ' (' + peripheral.serial + ')' }", peripheral, class: 'button'
                    - if (current_user == @item.user) || can?(:manage, Item)
                      = link_to add_peripheral_option_item_path, class: 'button is-link', id: 'add_peripheral' do
                        %span.icon
                          %i.fas.fa-plus
              %tr
                %th Comments
                %td
                  = @item.comment

              - unless @item.retired_date.blank?
                %tr
                  %th Retired Date
                  %td
                    = @item.retired_date.strftime("%d %B %Y")

      .field.is-horizontal
        .field-body
          - if can?(:manage, Item) || current_user == @item.user
            .field.is-grouped.is-grouped-left
              .control
                - if @parents.blank?
                  = link_to 'Edit', edit_item_path, class: 'button is-link'
                - else
                  = link_to 'Edit', edit_item_path(@item, is_peripheral: true), class: 'button is-link'
          .field.is-grouped.is-grouped-right
            .control
              = link_to 'Back', items_path, class: 'button is-block is-light'
            .control
              = link_to 'Book or Reserve', new_item_booking_path(item_id: @item.id), class:'button is-link is-block'

    %br
    %br
    - if @item.user == current_user || current_user.admin?
      %p.title.has-text-centered Bookings History
      %table#assets.table.is-striped.is-bordered
        %thead
          %tr
            %th ID
            %th Asset
            %th Start Date-Time
            %th End Date-Time
            %th Location
            %th Reason
            %th Booked By
            %th Status
        %tbody
          - @bookings.reverse_each do |booking|
            %tr
              %td.has-text-centered= booking.id
              %td.has-text-centered= @item.name
              %td.has-text-centered= booking.start_datetime.strftime("%d %b %Y - %I:%M %p")
              %td.has-text-centered= booking.end_datetime.strftime("%d %b %Y - %I:%M %p")
              %td.has-text-centered= booking.next_location
              %td.has-text-centered= booking.reason
              %td.has-text-centered= link_to booking.user.givenname, booking.user
              %td.has-text-centered
                = render 'bookings/booking_status', booking: booking