Asset Management/config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users

  resources :categories, except: :show do
    get 'filter', on: :collection
    post 'new_peripheral', on: :member
  end

  resources :users do
    get 'manager', on: :collection
  end

  resources :user_home_categories, except: %i[show edit update]

  resources :combined_bookings, only: [] do
    member do
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :bookings, except: %i[new show] do
    collection do
      get 'requests'
      get 'accepted'
      get 'ongoing'
      get 'completed'
      get 'rejected'
      get 'late'
    end

    member do
      get 'booking_returned'
      put 'set_booking_rejected'
      put 'set_booking_accepted'
      put 'set_booking_returned'
      put 'set_booking_cancelled'
    end
  end

  resources :items do
    resources :bookings, except: %i[index show] do
      collection do
        get 'start_date'
        get 'end_date'
        get 'peripherals'
      end
    end

    collection do
      get 'import'
      post 'import_file'
      get 'manager'
      put 'update_manager_multiple'
      post 'change_manager_multiple'
      put 'update_manager_multiple_and_delete'
      get 'change_manager_multiple_and_delete'
    end

    member do
      get 'add_peripheral_option'
      get 'choose_peripheral'
      post 'add_peripheral'
      get 'add_parents'
      post 'add_parents_complete'
    end
  end

  resources :notifications, only: :index do
    put :mark_as_read, on: :collection
  end

  root to: 'home#index'

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Asset Management/app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id             :integer          not null, primary key
#  name           :string
#  icon           :string
#  has_peripheral :boolean
#  is_peripheral  :boolean
#
# Indexes
#
#  index_categories_on_name  (name) UNIQUE
#

# Category model
class Category < ApplicationRecord
  has_many :items
  has_many :user_home_categories
  has_many :users, through: :user_home_categories

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }

  scope :all_name, -> { pluck(:name) }
end

Asset Management/app/controllers/categories_controller.rb
# frozen_string_literal: true

# Categories controller
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/filter
  def filter
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories/new
  def new_peripheral
    # Get the caregory the peripheral category should belong to
    parent_category = Category.find_by_id(params[:id])
    # Mark the category as having a peripheral category.
    parent_category.has_peripheral = 1

    # Deep copy category
    category = Category.find_by_id(params[:id]).dup
    # Add peripherals to end of name
    category.name = category.name.humanize.gsub(/\b('?[a-z])/) { Regexp.last_match(1).capitalize }.strip + ' - Peripherals'

    # Format icon tag correctly for database and set in record
    if (!category.icon.include? 'material-icons') && !category.icon.empty?
      category.icon = category.icon.chomp('"></i>') + ' fa-6x"></i><i class="material-icons">P</i>'
    else
      category.icon = category.icon.chomp('</i>') + 'P</i>' unless category.icon.empty?
    end

    # Set whether categories have peripheral categories
    category.is_peripheral = 1
    category.has_peripheral = 0

    # Save the categories
    if category.save && parent_category.save
      redirect_to categories_path, notice: 'Peripheral category successfully created'
    end
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  def create
    @category = Category.new(category_params)

    # Checks whether the category already exists
    if Category.exists?(name: @category.name.titleize.strip)
      redirect_to new_category_path, alert: 'Category already exists.'

    # If category doesn't exist
    elsif @category.name =~ /^[a-zA-Z0-9 _.,!()+=`,"&@$#%*-]{4,50}$/

      # Set its name and format
      @category.name = @category.name.humanize.gsub(/\b('?[a-z])/) { Regexp.last_match(1).capitalize }.strip

      # Font awesome icon
      if (!@category.icon.include? 'material-icons') && !@category.icon.empty?
        @category.icon = @category.icon.chomp('"></i>') + ' fa-6x"></i>'
      end

      # Set that category does not have or is not a peripheral category
      @category.is_peripheral = 0
      @category.has_peripheral = 0

      # Create a duplicate category for the new category's peripherals
      if params[:want_peripheral].to_i == 1

        # Set category as having a peripheral category
        @category.has_peripheral = 1

        # Create the child/peripheral category
        category = Category.new(category_params)
        category.name = @category.name + ' - Peripherals'

        # Format icon tag
        if (!category.icon.include? 'material-icons') && !category.icon.empty?
          category.icon = @category.icon.chomp('"></i>') + ' fa-6x"></i><i class="material-icons">P</i>'
        else
          category.icon = @category.icon.chomp('</i>') + 'P</i>'
        end

        # Set whether categories have peripheral categories
        category.is_peripheral = 1
        category.has_peripheral = 0

        # Save the created category
        category.save
      end

      # Save the new category and handle errors
      if @category.save
        redirect_to categories_path, notice: 'Category was successfully created.'
      end
    else
      redirect_to new_category_path, alert: 'Category name does not meet requirements.'
    end
  end

  # PATCH/PUT /categories/1
  def update
    @category.update(category_params)
    redirect_to categories_path, notice: 'Category was successfully updated.'
  rescue StandardError
    redirect_to request.referrer, alert: 'Category already exist.'
  end

  # DELETE /categories/1
  def destroy
    # Get items in the category
    items = Item.where(category_id: @category.id)

    if items.blank?
      # Delete user favourites which belong to this category
      UserHomeCategory.where(category_id: @category.id).destroy_all

      begin
        # Destroy child/peripheral category
        if @category.is_peripheral
          parent_category = Category.where(name: @category.name[0..-15]).first
          parent_category.has_peripheral = 0
          parent_category.save
        end
        # Delete the category
        @category.destroy
        redirect_to categories_url, notice: 'Category was successfully deleted.'
      end
    else
      redirect_to categories_path, alert: 'Cannot delete category because it is currently in use for an asset.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit!
  end
end

Asset Management/app/views/categories/edit.html.haml
- content_for :title, "Editing #{@category.name}"

%section.hero
  .hero-body
    .container.has-text-centered
      = render partial: 'layouts/flash'
      
      .column.is-10.is-offset-1
        %h3.title Editing #{@category.name}
        .box
          = simple_form_for(@category) do |f|
            = f.error_notification

            .field.is-horizontal
              .field-label.is-normal
                %label.label Category
              .field-body
                .field
                  %p.control.is-expanded
                    = f.input :name, label: false, required: '', placeholder: 'Category', input_html: {class: 'input'}
            .field.is-horizontal
              .field-label.is-normal
                %label.label Icon
              .field-body
                .field
                  %p.control.is-expanded
                    = f.input :icon, label: false, placeholder: 'Icon tag', input_html: {class: 'input'}
                  %p.help
                    Find an icon from the providers below, and copy their HTML tag. e.g. <strong>
                    :escaped
                      <i class="fas fa-edit"><i>
                    </strong>
                  %p.help
                    = link_to 'Font Awesome', 'https://fontawesome.com/icons?d=gallery'
                    or
                    = link_to 'Material icons', 'https://material.io/icons/'
            %br
            .field.is-horizontal
              .field-label.has-text-left
                -#Left empty for spacing
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Cancel' , categories_path, class: 'button is-block is-light'
                  .control
                    = f.submit 'Save changes', class: 'button is-block is-success'

Asset Management/app/views/categories/filter.haml
- content_for :title, "Categories"

%br/
.container.is-fluid
  = render partial: 'layouts/flash'

  %p.title.has-text-centered Current categories
  - if can?(:create, Category)
    %p.title.has-text-centered
      = link_to 'Create new', new_category_path, class: 'button is-success'
  %table#categories.table.is-striped.is-bordered
    %thead
      %tr
        %th Category
    %tbody
      - @categories.each do |category|
        %tr
          %td.has-text-centered
            = link_to category.name, items_path(category_name: category.name)

Asset Management/app/views/categories/index.html.haml
- content_for :title, "Categories"

%br/
.container.is-fluid
  = render partial: 'layouts/flash'

  %p.title.has-text-centered Current categories
  %p.title.has-text-centered
    = link_to 'Create new', new_category_path, class: 'button is-success'

  %table#categories.table.is-striped.is-bordered
    %thead
      %tr
        %th Category
        %th Icon
        %th Action
    %tbody
      - @categories.each do |category|
        %tr
          %td.has-text-centered
            = category.name
          %td.has-text-centered
            - if category.icon?
              %span.icon.is-normal
                = raw "#{category.icon.gsub('fa-6x', 'fa-2x')}"
            - else
              %span.icon.is-normal
                %i.far.fa-question-circle.fa-2x
          %td
            .field.is-grouped.is-grouped-centered
              - if !category.is_peripheral && !category.has_peripheral
                %p.control
                  = link_to new_peripheral_category_path(id: category.id), method: :post, data: { confirm: 'Are you sure you want to create a Peripheral category for this category?' }, class: 'button is-primary' do
                    %span.icon
                      %i.fas.fa-plus
                    %span Create Peripheral Category
              %p.control
                = link_to edit_category_path(category), class: 'button is-link' do
                  %span.icon
                    %i.fas.fa-edit
                  %span Edit
              %p.control
                = link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger', id: "delete_category_#{category.id}" do
                  %span.icon
                    %i.fas.fa-trash
                  %span Delete

Asset Management/app/views/categories/new.html.haml
- content_for :title, "Create category"

%section.hero
  .hero-body
    .container.has-text-centered
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .columns
          .column.is-4.is-offset-4
            .notification.is-danger.has-text-centered
              %button.delete
              = msg

      .column.is-10.is-offset-1
        %h3.title Create category
        .box
          = simple_form_for(@category) do |f|
            = f.error_notification

            .field.is-horizontal
              .field-label.is-normal
                %label.label Category
              .field-body
                .field
                  %p.control.is-expanded
                    = f.input :name, label: false, required: '', placeholder: 'Category', input_html: {class: 'input', maxlength: 50}
                  %p.help Between 4-50 characters, characters allowed: alpha-numeric &_.,!()+=`,"@$#%*-

            .field.is-horizontal
              .field-label.is-normal
                %label.label Icon
              .field-body
                .field
                  %p.control.is-expanded
                    = f.input :icon, label: false, placeholder: 'Icon tag', input_html: {class: 'input'}
                  %p.help
                    Find an icon from the providers below, and copy their HTML tag. e.g. <strong>
                    :escaped
                      <i class="fas fa-edit"></i>
                    </strong>
                  %p.help
                    = link_to 'Font Awesome', 'https://fontawesome.com/icons?d=gallery', target: :_blank
                    or
                    = link_to 'Material icons', 'https://material.io/icons/', target: :_blank


            .field.is-horizontal
              .field-label.is-normal
              .field-body
                .field
                  %p.control.is-expanded
                    = f.input :want_peripheral, as: :check_boxes, label: false  do
                      = check_box_tag 'want_peripheral'
                      %label{:for => "want_peripheral"} Create a peripheral category under this category
            %br
            .field.is-horizontal
              .field-label.has-text-left
                -#Left empty for spacing
              .field-body
                .field.is-grouped.is-grouped-right
                  .control
                    = link_to 'Cancel' , categories_path, class: 'button is-block is-light'
                  .control
                    = f.submit 'Create category', class: 'button is-block is-link'